-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.events
(
    event_id integer NOT NULL DEFAULT nextval('events_event_id_seq'::regclass),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    location character varying COLLATE pg_catalog."default" NOT NULL,
    date timestamp without time zone NOT NULL,
    CONSTRAINT "PK_1b77463a4487f09e798dffcb43a" PRIMARY KEY (event_id)
);

CREATE TABLE IF NOT EXISTS public.fighter_stats
(
    stats_id integer NOT NULL DEFAULT nextval('fighter_stats_stats_id_seq'::regclass),
    victory boolean NOT NULL,
    victory_type character varying COLLATE pg_catalog."default" NOT NULL,
    "fighterFighterId" integer,
    "fightFightId" integer,
    CONSTRAINT "PK_222063d6efc3e3fc874d6b5be34" PRIMARY KEY (stats_id)
);

CREATE TABLE IF NOT EXISTS public.fighters
(
    fighter_id integer NOT NULL DEFAULT nextval('fighters_fighter_id_seq'::regclass),
    weight_class character varying COLLATE pg_catalog."default" NOT NULL,
    nationality character varying COLLATE pg_catalog."default" NOT NULL,
    team character varying COLLATE pg_catalog."default" NOT NULL,
    age character varying COLLATE pg_catalog."default" NOT NULL,
    height numeric(5, 2) NOT NULL,
    weight numeric(5, 2) NOT NULL,
    "DOB" date NOT NULL,
    "createdAt" timestamp without time zone NOT NULL DEFAULT now(),
    "updatedAt" timestamp without time zone NOT NULL DEFAULT now(),
    fristname character varying COLLATE pg_catalog."default" NOT NULL,
    lastname character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_dcc657584128752707f87b3aad4" PRIMARY KEY (fighter_id)
);

CREATE TABLE IF NOT EXISTS public.fights
(
    fight_id integer NOT NULL DEFAULT nextval('fights_fight_id_seq'::regclass),
    "event_ id" integer,
    "fighter1FighterId" integer,
    "fighter2FighterId" integer,
    CONSTRAINT "PK_61dc76f2c217d0e20394da69392" PRIMARY KEY (fight_id)
);

CREATE TABLE IF NOT EXISTS public.ranking
(
    ranking_id integer NOT NULL DEFAULT nextval('ranking_ranking_id_seq'::regclass),
    "position" integer NOT NULL,
    "fighterFighterId" integer,
    CONSTRAINT "PK_deb95c934f7d9d99536ec7a857a" PRIMARY KEY (ranking_id)
);

ALTER TABLE IF EXISTS public.fighter_stats
    ADD CONSTRAINT "FK_356a4649e805c921c5d045e659d" FOREIGN KEY ("fightFightId")
    REFERENCES public.fights (fight_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fighter_stats
    ADD CONSTRAINT "FK_aabe19b40f1c2c500637c336a5b" FOREIGN KEY ("fighterFighterId")
    REFERENCES public.fighters (fighter_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fights
    ADD CONSTRAINT "FK_2854273bd758448a46451acabb0" FOREIGN KEY ("event_ id")
    REFERENCES public.events (event_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fights
    ADD CONSTRAINT "FK_307b5a092fd7c1b1243679dc276" FOREIGN KEY ("fighter2FighterId")
    REFERENCES public.fighters (fighter_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fights
    ADD CONSTRAINT "FK_4ea31f14de330ffaf8908b9d2d2" FOREIGN KEY ("fighter1FighterId")
    REFERENCES public.fighters (fighter_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ranking
    ADD CONSTRAINT "FK_5e37e559a6bdd3fc92d65c80bbd" FOREIGN KEY ("fighterFighterId")
    REFERENCES public.fighters (fighter_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;